title = "portfoliov2"
theme = "nightfall"
languageCode = "en-us"
baseURL = "https://example.org/"
copyright = "Sample custom notice © {year}"


[params]
user = "hello"
hostname = "gohugo.io"

  [params.author]
    name = "Jonathan KERK"
    avatar = "/avatar.png"
    avatarSize = "size-m"
    email = "contact@jonathankerk.com"
    avatarFirst = false