theme = "nightfall"
languageCode = "en-us"
baseURL = "https://jonathankerk.com/"

[params]
user = "hello"
hostname = "jonathankerk.com"

  [params.author]
    name = "Jonathan KERK"
    email = "contact@jonathankerk.com"
    avatarFirst = false

  [[params.social]]
      key = 0
      name = "linkedin"
      url = "https://linkedin.com/in/jonathan-kerk"
      target = "_blank"
      aria = "LinkedIn"

  [[params.social]]
      key = 1
      name = "email"
      url = "mailto:contact@jonathankerk.com"

  [[params.social]]
      key = 2
      name = "resume"
      url = ""

  [[params.social]]
      key = 3
      name = "github"
      url = "https://github.com/jonzxz"
      target = "_blank"
      aria = "GitHub Profile"

[menu]
  [[menu.header]]
  name = "about"
  weight = 1
  url = "/about"

  [[menu.header]]
  name = "posts"
  weight = 0
  url = "/posts"